DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user_likes;
DROP TABLE IF EXISTS post_comments;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  image TEXT NULL,
  name TEXT NULL,
  nickname TEXT NULL,
  teamid TEXT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  likes INTEGER NOT NULL,
  dislikes INTEGER NOT NULL,
  comments INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE user_likes (
  userid INTEGER NOT NULL,
  postid INTEGER NOT NULL,
  liked INTEGER NOT NULL,
  disliked INTEGER NOT NULL,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userid) REFERENCES user (id),
  FOREIGN KEY (postid) REFERENCES post (id),
  PRIMARY KEY (userid, postid)
);
 
CREATE TABLE post_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  postid INTEGER NOT NULL,
  userid INTEGER NOT NULL,
  name TEXT NOT NULL,
  comment TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userid) REFERENCES user (id),
  FOREIGN KEY (postid) REFERENCES post (id)
);